name: build
on: [push, pull_request]
env:
  GO111MODULE: on
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Get dependencies
      run: just mod
    - name: Build code
      run: just build
    - name: Test code
      run: just test '-v -count=1'

  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: --tests ./...

  vet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Vet source
      run: just vet
